name: Build/Test/Release
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - name: Install Ubuntu dependencies
        run: sudo apt-get update -y && sudo apt-get install -y libreadline-dev libboost-container-dev libboost-program-options-dev libboost-serialization-dev patchelf automake

      - name: Download cache of third-party build
        run: aws s3 sync s3://cartesi-ci/${GITHUB_REPOSITORY}/cache/build-00007 ./build
        env:
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build third-party dependencies
        run: make -j$(nproc) dep

      - name: Fix build dependencies permissions
        run: chmod +x ./build/`uname`_`uname -m`/bin/protoc ./build/`uname`_`uname -m`/bin/grpc_cpp_plugin

      - name: Cache third-party build
        run: aws s3 sync ./build s3://cartesi-ci/${GITHUB_REPOSITORY}/cache/build-00007
        env:
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build
        run: make -j$(nproc)

      - name: Install [/opt/cartesi]
        run: make install

      - name: Upload emulator
        uses: actions/upload-artifact@master
        with:
          name: emulator
          path: /opt/cartesi

  test:
    name: Test
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Download emulator
        uses: actions/download-artifact@master
        with:
          name: emulator
          path: /opt/cartesi

      - name: Install Ubuntu dependencies
        run: sudo apt-get update -y && sudo apt-get install -y libboost-program-options1.65.1 libboost-serialization1.65.1

      - name: Set current git organization env var
        id: git_org
        run: echo "::set-output name=current_organization::$(echo ${GITHUB_REPOSITORY} | cut -d '/' -f 1)"

      - name: Download [rootfs.ext2]
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: ${{ steps.git_org.outputs.current_organization }}/image-rootfs
          tag: 'v0.2.0'
          file: rootfs.ext2
          token: ${{ secrets.CI_TOKEN }}

      - name: Download [kernel.bin]
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: ${{ steps.git_org.outputs.current_organization }}/image-kernel
          tag: 'v0.4.0'
          file: kernel.bin
          token: ${{ secrets.CI_TOKEN }}

      - name: Download [rom.bin]
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: ${{ steps.git_org.outputs.current_organization }}/machine-emulator-rom
          tag: 'v0.2.0'
          file: rom.bin
          token: ${{ secrets.CI_TOKEN }}

      - name: Fix artifact permissions
        run: |
          chmod +x /opt/cartesi/bin/lua*
          chmod +x /opt/cartesi/bin/cartesi-machine*

      - name: Simple Boot
        run: /opt/cartesi/bin/luapp5.3 /opt/cartesi/bin/cartesi-machine.lua --append-rom-bootargs="-- /bin/true"

      - name: Download test suite
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: ${{ steps.git_org.outputs.current_organization }}/machine-tests
          tag: 'v0.3.0'
          file: machine-tests-v0.3.0.tar.gz
          token: ${{ secrets.CI_TOKEN }}

      - name: Untar test suite
        run: mkdir -p /opt/cartesi/tests && tar -xzf machine-tests-v0.3.0.tar.gz -C /opt/cartesi/tests

      - name: Run test suite
        run: /opt/cartesi/bin/luapp5.3 /opt/cartesi/bin/cartesi-machine-tests.lua --test-path=/opt/cartesi/tests run

  release:
    name: Release
    needs: test
    runs-on: ubuntu-18.04
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download emulator
        uses: actions/download-artifact@master
        with:
          name: emulator
          path: /opt/cartesi

      - name: Fix artifact permissions
        run: |
          chmod +x /opt/cartesi/bin/lua*
          chmod +x /opt/cartesi/bin/cartesi-machine*

      - name: Create TAR
        run: tar -czf machine-emulator-`uname`-${GITHUB_REF:10}.tar.gz -C /opt/cartesi .

      - name: Upload TAR to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: machine-emulator-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}

      - uses: actions/checkout@v1
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Image
        run: |
          docker build -t cartesi/machine-emulator:${GITHUB_REF:11} -f .github/workflows/Dockerfile /opt/cartesi
          docker push cartesi/machine-emulator:${GITHUB_REF:11}

      - name: Docker Alpine Image
        run: |
          docker build . -t cartesi/machine-emulator:${GITHUB_REF:11}-alpine -f .github/workflows/Dockerfile.alpine
          docker push cartesi/machine-emulator:${GITHUB_REF:11}-alpine
