name: Build/Test/Release
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - name: Install Ubuntu dependencies
        run: sudo apt-get update -y && sudo apt-get install -y libreadline-dev libboost-container-dev libboost-program-options-dev patchelf automake

      - name: Download cache of third-party build
        run: aws s3 sync s3://cartesi-ci/${GITHUB_REPOSITORY}/cache/build ./build
        env:
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build third-party dependencies
        run: make -j$(nproc) dep

      - name: Fix build dependencies permissions
        run: chmod +x ./build/`uname`_`uname -m`/bin/protoc ./build/`uname`_`uname -m`/bin/grpc_cpp_plugin

      - name: Cache third-party build
        run: aws s3 sync ./build s3://cartesi-ci/${GITHUB_REPOSITORY}/cache/build
        env:
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build
        run: make -j$(nproc)

      - name: Install [/opt/cartesi]
        run: make install

      - name: Upload emulator
        uses: actions/upload-artifact@master
        with:
          name: emulator
          path: /opt/cartesi

  test:
    name: Test
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Download emulator
        uses: actions/download-artifact@master
        with:
          name: emulator
          path: /opt/cartesi

      - name: Download [rootfs.ext2]
        run: wget https://github.com/cartesi/image-rootfs/releases/download/v0.1.0-rc.1/rootfs.ext2
      - name: Download [rom.bin]
        run: wget https://github.com/cartesi/machine-emulator-rom/releases/download/v0.1.0-rc.1/rom.bin
      - name: Download [kernel.bin]
        run: wget https://github.com/cartesi/image-kernel/releases/download/v0.1.0-rc.1/kernel.bin

      - name: Fix artifact permissions
        run: |
          chmod +x /opt/cartesi/bin/lua*
          chmod +x /opt/cartesi/bin/cartesi-machine*

      - name: Simple Boot
        run: /opt/cartesi/bin/luapp5.3 /opt/cartesi/lib/luapp/5.3/cartesi-machine.lua --cmdline="-- /bin/true" --batch

      - name: Download test suite
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: cartesi-corp/machine-tests
          tag: 'v0.1.1-pre3'
          file: machine-tests-v0.1.1-pre3.tar.gz
          token: ${{ secrets.CI_TOKEN }}

      - name: Untar test suite
        run: mkdir -p /opt/cartesi/tests && tar -xzf machine-tests-v0.1.1-pre3.tar.gz -C /opt/cartesi/tests

      - name: Run test suite
        run: /opt/cartesi/bin/luapp5.3 /opt/cartesi/lib/luapp/5.3/cartesi-machine-tests.lua /opt/cartesi/tests

  release:
    name: Release
    needs: test
    runs-on: ubuntu-18.04
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download emulator
        uses: actions/download-artifact@master
        with:
          name: emulator
          path: /opt/cartesi

      - name: Fix artifact permissions
        run: |
          chmod +x /opt/cartesi/bin/lua*
          chmod +x /opt/cartesi/bin/cartesi-machine*

      - name: Create TAR
        run: tar -czf machine-emulator-`uname`-${GITHUB_REF:10}.tar.gz -C /opt/cartesi .

      - name: Upload TAR to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: machine-emulator-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
